name: Install glaze
description: Install glaze for building test application
inputs:
  version:
    description: The desired glaze version to install
    required: false
    default: "5.0.0"
runs:
  using: composite
  steps:
    - run: |
        cd /tmp
        wget https://github.com/stephenberry/glaze/archive/v${{ inputs.version }}.tar.gz
        tar -zxf /tmp/v${{ inputs.version }}.tar.gz
        cd glaze-${{ inputs.version }}
        cmake .
        sudo cmake --install .
      shell: bash
